Refactor of nodeJS sdk design / dependencies and declaration to be more ts alike and up to date
openfoodfacts/openfoodfacts-nodejs pull request #365
Opened 2023-12-11 18:48 UTC by Valetek

### What
Updated the project architecture, how the package is exported / constructed and is dependencies

### Fixes bug(s)
- ts-standard full validation
- no ts error from wrong fetch declaration / overriding

2023-12-13 20:38 UTC, VaiTon commented on src/main.ts
> +  constructor (
Why did you remove the `fetch` parameter? It can be used in some SSR frameworks to make the server fetch the resources

2023-12-14 13:27 UTC, Valetek commented on src/main.ts
> +  constructor (
For what I could see, [openapi-fetch](https://openapi-ts.pages.dev/openapi-fetch/) already provide a default fetcher (which is nodeJS.fetch), and on there website I could see that there default fetcher was the fastest that can be used, so I removed it to not be overrided

Is there a case where it couldn't not work ? Should I implement it back ?

2023-12-22 19:26 UTC, VaiTon commented on src/main.ts
> +  constructor (
In SvelteKit (for example) you need to pass a custom `fetch` to be able to use the SSR correctly. We're using it for https://github.com/openfoodfacts/openfoodfacts-explorer

2023-12-23 18:26 UTC, Valetek commented on src/main.ts
> +  constructor (
Hello @VaiTon I put back fetch as an option in the constructor, but with inferred to avoid override of type

2024-01-06 15:58 UTC, VaiTon requested changes
Hey, here it is a second round of reviews

2024-01-06 15:58 UTC, VaiTon commented on README.md
> +const client = new OFF({ country: 'string' || null });
This should be an example, not the typing of the constructor.

2024-01-06 15:58 UTC, VaiTon commented on package.json
> +  "name": "openfoodfacts-nodejs-ts",
Why should we change the name of the package?

2024-01-06 15:58 UTC, VaiTon commented on src/main.ts
> +    this.baseUrl = 'https://world.openfoodfacts.org'
Why remove the `{options.country}` ?

2024-01-06 15:58 UTC, VaiTon commented on src/types.ts
> +export type Fetch = typeof fetch
I think this type could be removed. Is there any reason to keep it?

2024-01-06 15:58 UTC, VaiTon commented on tsconfig.json
> +      "dom",
We should not need DOM if we're working in pure NodeJS

2024-01-10 14:40 UTC, Valetek commented on package.json
> +  "name": "openfoodfacts-nodejs-ts",
I made the structure and the file working in and for ts, so in my point it make sense to rename it to "ts" to make people aware it's intended to also work for ts project 

For what I know ts packages work for ts and js, but always make it explicit when they are made to work for ts

2024-01-10 14:42 UTC, Valetek commented on src/main.ts
> +    this.baseUrl = 'https://world.openfoodfacts.org'
From my test (using fr country) it didn't seems to work, maybe I did it wrong, in case I will put it back

2024-01-10 14:45 UTC, Valetek commented on src/types.ts
> +export type Fetch = typeof fetch
Yes, by exemple in my own project (that is also why I m making this refacto) I need the Product type from the off sdk to be accessible cause I need to type my return function

My own product type (coming from the exported mongo database) isn't compatible with the sdk return so I need this type to make some data convertion

Yet it can be inferered from the return but making it visible is a good thing for some case as mine

2024-01-10 14:47 UTC, Valetek commented on tsconfig.json
> +      "dom",
The NodeJS fetch type was in conflit with the openapi-fetch packages, in this they are using the fetch type coming from dom and not from NodeJS

Before the refactoring the project was shouting a warning about fetch incompatible type, so using the fetch type coming from dom was the solution to be aligned with openapi-fetch packages

2024-01-10 15:16 UTC, Valetek commented
Hello @VaiTon, I made some new change about what you pointed out, aside for the point that need some more discussion

2024-03-01 10:50 UTC, teolemon commented
@VaiTon @Valetek arg, merge conflicts :-(

2024-03-01 15:11 UTC, Valetek commented
@teolemon gave a look, I can't do the merge myself ... @VaiTon did too much change and added lot of content on his branch for me to handle it, I think it would be better if he can have a look on his side, my branch is essencially about refactoring, I didn't add any special behavior

So unless he take a look on it I think my change will be lost here :') I will probably remove some of his work if I try to do it on my side

2025-01-05 20:53 UTC, closed without merging