feat: Add endpoint for /insights robotoff
openfoodfacts/openfoodfacts-nodejs pull request #553
Opened 2024-11-04 11:38 UTC by gciluffo

### What
- Ran Open API generation for Robotoff `npm run api:robotoff`
- Add endpoint for /insights 

### Screenshot

### Fixes bug(s)
- 

### Part of 
#541

2024-11-04 20:24 UTC, bengeois requested changes
Thanks ! I've suggested some changes

2024-11-04 20:24 UTC, bengeois commented on src/robotoff.ts
> +  async insights(query: InsightQuery) {
Could you type the return type of the `insight` function as it is also provided in the generated schema ?

2024-11-04 20:24 UTC, bengeois commented on src/robotoff.ts
We've started adding jsdoc on some functions, could you add it on this `insight` function ?
You can find an example here https://github.com/openfoodfacts/openfoodfacts-nodejs/blob/1457b456bd94484ae259fc2fa88e0b5fe05de621/src/nutripatrol.ts#L107-L117

2024-11-05 07:32 UTC, gciluffo commented on src/robotoff.ts
> +  async insights(query: InsightQuery) {
It looks like the return type is already inferred from openapi-fetch initialized on line 13? Which was why I didnt explicitly type this.

2024-11-05 07:44 UTC, gciluffo commented on src/robotoff.ts
Updated. Doesnt look like theres any error object defined in the open-api spec for this endpoint so its just the input and output for now.

2024-11-05 07:44 UTC, gciluffo commented on src/robotoff.ts
> +  async insights(query: InsightQuery) {
Updated

2024-11-05 14:59 UTC, bengeois commented on src/robotoff.ts
> +  async insights(query: InsightQuery) {
You're right, this endpoint has an inferred type but it's not always the case. It will help to prevent potential errors if the schema changes or if TypeScript doesn’t infer the type accurately in other contexts

2024-11-05 15:17 UTC, bengeois commented
@all-contributors please add @gciluffo for code

2024-11-05 15:17 UTC, bengeois approved these changes

2024-11-05 15:18 UTC, merged

2024-11-05 15:21 UTC, bengeois commented
Thanks @gciluffo 🎉